
package presentacion;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;


public class Vista extends javax.swing.JFrame {
    
    private final Modelo modelo;
    private Controlador control;
    private ArrayList<JLabel> listaLblAux;

    public Vista(Modelo aThis) {
        modelo = aThis;
        initComponents();
        crearEtiquetasTablero();
        creatBotonesNumericos();
        this.setLocationRelativeTo(null);
        asignarEventos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelBotonNum = new javax.swing.JPanel();
        btnNum1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        pnlCeldas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel12.setBackground(new java.awt.Color(204, 204, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(700, 690));
        jPanel12.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setText("SUDOKU");
        jPanel12.add(jLabel1);
        jLabel1.setBounds(280, 20, 200, 40);

        panelBotonNum.setLayout(null);

        btnNum1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnNum1.setText("1");
        btnNum1.setPreferredSize(new java.awt.Dimension(40, 40));
        btnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum1ActionPerformed(evt);
            }
        });
        panelBotonNum.add(btnNum1);
        btnNum1.setBounds(70, 10, 50, 40);

        jPanel12.add(panelBotonNum);
        panelBotonNum.setBounds(10, 570, 490, 110);

        jPanel3.setLayout(null);

        btnNuevo.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        btnNuevo.setText("Nuevo");
        jPanel3.add(btnNuevo);
        btnNuevo.setBounds(6, 25, 168, 46);

        btnReiniciar.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        jPanel3.add(btnReiniciar);
        btnReiniciar.setBounds(6, 89, 168, 46);

        btnBorrar.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        btnBorrar.setText("Borrar");
        jPanel3.add(btnBorrar);
        btnBorrar.setBounds(6, 153, 168, 46);

        jPanel12.add(jPanel3);
        jPanel3.setBounds(510, 80, 180, 590);

        pnlCeldas.setBackground(new java.awt.Color(102, 102, 255));
        pnlCeldas.setLayout(null);
        jPanel12.add(pnlCeldas);
        pnlCeldas.setBounds(10, 80, 490, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNum1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelBotonNum;
    private javax.swing.JPanel pnlCeldas;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel lblCeldas[][];
    private javax.swing.JButton btnNumeros[];
    
    private void asignarEventos() {
        btnNuevo.addActionListener(getControl());
    }

    public Controlador getControl() {
        if(control==null){
            control = new Controlador(this);
        }
        return control;
    }

    public JButton getBtnNuevo() {
        return btnNuevo;
    }

    public Modelo getModelo() {
        return modelo;
    }

    private void crearEtiquetasTablero() {
        lblCeldas = new JLabel[9][9];
        listaLblAux = new ArrayList<>();
        
         int x = 9;
         int y = 9;
         int n = 0;
         int dimension=50;
         
        //Columna - Y
        for (int c = 0; c < 9; c++) {
            //Filas - X
            for (int f = 0; f < 9; f++) {
                lblCeldas[f][c] = new JLabel();
                pnlCeldas.add(lblCeldas[f][c]);
                lblCeldas[f][c].setBounds(x, y, dimension, dimension);
                lblCeldas[f][c].setBackground(new java.awt.Color(242, 242, 242));
                lblCeldas[f][c].setForeground(new java.awt.Color(0, 0, 0));
                lblCeldas[f][c].setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
                lblCeldas[f][c].setOpaque(true);
                lblCeldas[f][c].setCursor(new Cursor(Cursor.HAND_CURSOR));
                lblCeldas[f][c].setBorder(BorderFactory.createLineBorder(new Color(102,102,255), 1));
                lblCeldas[f][c].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);        
                x += dimension;
                
                lblCeldas[f][c].setToolTipText("");
                if((f+1)%3 == 0){
                    x += 9;
                }
                asignarEventoCelda(lblCeldas[f][c]);
            }
            x = 9;
            y += dimension;
            if((c+1)%3 == 0){
                    y += 10;
            }
        }
    } 
    private void creatBotonesNumericos() {
        btnNumeros = new JButton[10];
        int x = 70;
        int y = 10;
        int dimension = 40;
        int ubicacionArreglo = 0;
        for (int c = 0; c < 2; c++) {
            for (int f = 0; f < 5; f++) {
                btnNumeros[ubicacionArreglo] = new JButton();
                btnNumeros[ubicacionArreglo].setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
                panelBotonNum.add(btnNumeros[ubicacionArreglo]);
                btnNumeros[ubicacionArreglo].setText(String.valueOf(ubicacionArreglo));
                btnNumeros[ubicacionArreglo].setBounds(x,y,dimension,dimension);
                x+=dimension;
                ubicacionArreglo++;
            }
            x=70;
            y+=dimension;
        }
    }
    public void asignarEventoCelda(JLabel Celdas){
        Celdas.addMouseListener(getControl());
    }
    
    public int[] pressed(JLabel Celdas){
        int retorno[] = new int[2];
        for(JLabel jLbl : listaLblAux){
            jLbl.setBackground(new java.awt.Color(242, 242, 242));
            jLbl.setForeground(new java.awt.Color(0, 0, 0));
            jLbl.setBorder(BorderFactory.createLineBorder(new Color(102,102,255), 1));
        }
        listaLblAux.clear();
        
        for (int f = 0; f < 9; f++) {
            for (int c = 0; c < 9; c++) {
                if(lblCeldas[f][c] == Celdas){
                    listaLblAux.add(lblCeldas[f][c]);
                    lblCeldas[f][c].setBorder(BorderFactory.createLineBorder(Color.WHITE, 2));
                    lblCeldas[f][c].setBackground(Color.BLUE);
                    lblCeldas[f][c].setForeground(Color.WHITE);
                    retorno[0]=f;
                    retorno[1]=c;
                }
            }
        }
        return retorno;
    }

    public void nuevoTableroJuego(int[][] tableroBase) {
        for(int c=0;c<9;c++){
            for(int f=0;f<9;f++){
                int celdaActual = tableroBase[f][c];
                if(celdaActual!=0){
                    lblCeldas[f][c].setText(String.valueOf(celdaActual));
                    lblCeldas[f][c].setEnabled(false);
                }
                else{
                    lblCeldas[f][c].setEnabled(true);
                }
            }
        }
    }
    
    public void dibujoTablero(){
        
    }

    
}
